spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=admin
spring.datasource.password=COLOQUE_SUA_SENHA_AQUI

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=SEU_USERNAME_AQUI
spring.mail.password=SUA_SENHA_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true